name: RPGProfiles
version: '${project.version}'
main: com.profilesplus.RPGProfiles
api-version: 1.19
author: Kilo
description: A plugin to manage multiple profiles for players.
softdepend:
  - MMOItems
  - Vault
  - PlaceholderAPI
  - MythicMobs
depend:
  - MMOCore
  - MythicLib
commands:
  rpgprofiles:
    usage: /rpgprofiles reload
    description: "The main command of the plugin!"
  saveProfiles:
    description: Save the current profiles!
    usage: /saveProfiles or /saveProfiles <player>
  profiles:
    description: Opens the profiles menu.
    usage: /<command>
  createprofile:
    description: Creates a new profile with the given display name and class name.
    usage: /<command> <display name> <class name>
  removeProfile:
    description: Remove a profile <integer> is the number of the slot it uses
    usage: /removeProfile <number>

permissions:
  rpgprofiles.commands.profiles:
    description: Allows the player to use the /profiles command.
    default: true
  rpgprofiles.commands.createprofile:
    description: Allows the player to use the /createprofile command.
    default: true
  rpgprofiles.commands.removeprofile:
    default: true
  rpgprofiles.default.default:
    default: not op
  rpgprofiles.default.Ten:
    default: op